// Generated by uniffi-bindgen-react-native
#include "react-native-bdk-sdk.h"
#include "generated/bdk_ffi.hpp"

namespace bdksdk {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeBdkFfi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}