"use strict";

// Generated by uniffi-bindgen-react-native

import { TurboModuleRegistry } from 'react-native';
export default TurboModuleRegistry.getEnforcing('BdkSdk');
//# sourceMappingURL=NativeBdkSdk.js.map