use bdk_ffi::*;

// ═══════════════════════════════════════════════════════════════════════════════
//  address_from_script
// ═══════════════════════════════════════════════════════════════════════════════

#[test]
fn address_from_script_p2wpkh_mainnet() {
    // bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4
    let script_hex = "0014751e76e8199196d454941c45d1b3a323f1433bd6";
    let addr = address_from_script(script_hex.into(), Network::Bitcoin).unwrap();
    assert_eq!(addr, "bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4");
}

#[test]
fn address_from_script_p2wpkh_testnet() {
    let script_hex = "0014751e76e8199196d454941c45d1b3a323f1433bd6";
    let addr = address_from_script(script_hex.into(), Network::Testnet).unwrap();
    assert_eq!(addr, "tb1qw508d6qejxtdg4y5r3zarvary0c5xw7kxpjzsx");
}

#[test]
fn address_from_script_p2pkh_mainnet() {
    let script_hex = "76a91477bff20c60e522dfaa3350c39b030a5d004e839a88ac";
    let addr = address_from_script(script_hex.into(), Network::Bitcoin).unwrap();
    assert!(addr.starts_with('1'));
}

#[test]
fn address_from_script_p2tr_mainnet() {
    let script_hex = "5120a60869f0dbcf1dc659c9cecbee090f21a5a2528c80e6d6332edb02fc5879e27f";
    let addr = address_from_script(script_hex.into(), Network::Bitcoin).unwrap();
    assert!(addr.starts_with("bc1p"));
}

#[test]
fn address_from_script_invalid_hex() {
    let result = address_from_script("not_hex".into(), Network::Bitcoin);
    assert!(result.is_err());
}

#[test]
fn address_from_script_empty_script() {
    let result = address_from_script("".into(), Network::Bitcoin);
    assert!(result.is_err());
}

#[test]
fn address_from_script_op_return() {
    let script_hex = "6a0b68656c6c6f20776f726c64";
    let result = address_from_script(script_hex.into(), Network::Bitcoin);
    assert!(result.is_err());
}

// ═══════════════════════════════════════════════════════════════════════════════
//  validate_descriptor
// ═══════════════════════════════════════════════════════════════════════════════

#[test]
fn validate_descriptor_valid() {
    // Use a descriptor generated by the SDK itself (known valid format)
    let desc = create_descriptor_from_string(
        "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about".into(),
        DescriptorTemplate::BIP84,
        KeychainKind::External,
        Network::Testnet,
    )
    .unwrap();
    assert!(validate_descriptor(desc, Network::Testnet));
}

#[test]
fn validate_descriptor_invalid_string() {
    assert!(!validate_descriptor("not a descriptor".into(), Network::Bitcoin));
}

#[test]
fn validate_descriptor_empty() {
    assert!(!validate_descriptor("".into(), Network::Bitcoin));
}

#[test]
fn validate_descriptor_wrong_network() {
    // Generate a testnet descriptor, validate against mainnet
    let desc = create_descriptor_from_string(
        "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about".into(),
        DescriptorTemplate::BIP84,
        KeychainKind::External,
        Network::Testnet,
    )
    .unwrap();
    // Descriptors with tprv are testnet-only, should fail on mainnet
    assert!(!validate_descriptor(desc, Network::Bitcoin));
}

// ═══════════════════════════════════════════════════════════════════════════════
//  create_descriptor_from_string
// ═══════════════════════════════════════════════════════════════════════════════

const TEST_MNEMONIC: &str = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";

#[test]
fn create_descriptor_from_string_bip84_external() {
    let desc = create_descriptor_from_string(
        TEST_MNEMONIC.into(),
        DescriptorTemplate::BIP84,
        KeychainKind::External,
        Network::Testnet,
    )
    .unwrap();
    assert!(desc.starts_with("wpkh("), "expected wpkh descriptor, got: {}", desc);
    // BDK outputs xpub with fingerprint+path prefix, child derivation is /0/*
    assert!(desc.contains("/84'/1'/0'"), "expected BIP84 testnet path in fingerprint, got: {}", desc);
    assert!(desc.contains("/0/*)"), "expected external child path /0/*, got: {}", desc);
}

#[test]
fn create_descriptor_from_string_bip84_internal() {
    let desc = create_descriptor_from_string(
        TEST_MNEMONIC.into(),
        DescriptorTemplate::BIP84,
        KeychainKind::Internal,
        Network::Testnet,
    )
    .unwrap();
    assert!(desc.starts_with("wpkh("), "expected wpkh descriptor, got: {}", desc);
    assert!(desc.contains("/84'/1'/0'"), "expected BIP84 testnet path, got: {}", desc);
    assert!(desc.contains("/1/*)"), "expected internal child path /1/*, got: {}", desc);
}

#[test]
fn create_descriptor_from_string_bip86() {
    let desc = create_descriptor_from_string(
        TEST_MNEMONIC.into(),
        DescriptorTemplate::BIP86,
        KeychainKind::External,
        Network::Bitcoin,
    )
    .unwrap();
    assert!(desc.starts_with("tr("), "expected tr descriptor, got: {}", desc);
    assert!(desc.contains("/86'/0'/0'"), "expected BIP86 mainnet path, got: {}", desc);
    assert!(desc.contains("/0/*)"), "expected external child path, got: {}", desc);
}

#[test]
fn create_descriptor_from_string_bip44() {
    let desc = create_descriptor_from_string(
        TEST_MNEMONIC.into(),
        DescriptorTemplate::BIP44,
        KeychainKind::External,
        Network::Bitcoin,
    )
    .unwrap();
    assert!(desc.starts_with("pkh("), "expected pkh descriptor, got: {}", desc);
    assert!(desc.contains("/44'/0'/0'"), "expected BIP44 mainnet path, got: {}", desc);
    assert!(desc.contains("/0/*)"), "expected external child path, got: {}", desc);
}

#[test]
fn create_descriptor_from_string_bip49() {
    let desc = create_descriptor_from_string(
        TEST_MNEMONIC.into(),
        DescriptorTemplate::BIP49,
        KeychainKind::External,
        Network::Bitcoin,
    )
    .unwrap();
    assert!(desc.starts_with("sh(wpkh("), "expected sh(wpkh) descriptor, got: {}", desc);
    assert!(desc.contains("/49'/0'/0'"), "expected BIP49 mainnet path, got: {}", desc);
    assert!(desc.contains("/0/*)"), "expected external child path, got: {}", desc);
}

#[test]
fn create_descriptor_from_string_invalid_mnemonic() {
    let result = create_descriptor_from_string(
        "invalid mnemonic words here".into(),
        DescriptorTemplate::BIP84,
        KeychainKind::External,
        Network::Testnet,
    );
    assert!(result.is_err());
}

#[test]
fn create_descriptor_from_string_matches_object_api() {
    let desc_from_string = create_descriptor_from_string(
        TEST_MNEMONIC.into(),
        DescriptorTemplate::BIP84,
        KeychainKind::External,
        Network::Testnet,
    )
    .unwrap();

    let mnemonic = std::sync::Arc::new(Mnemonic::from_string(TEST_MNEMONIC.into()).unwrap());
    let desc_from_object = create_descriptor(
        mnemonic,
        DescriptorTemplate::BIP84,
        KeychainKind::External,
        Network::Testnet,
    )
    .unwrap();

    assert_eq!(desc_from_string, desc_from_object);
}

#[test]
fn create_descriptor_from_string_result_validates() {
    let desc = create_descriptor_from_string(
        TEST_MNEMONIC.into(),
        DescriptorTemplate::BIP84,
        KeychainKind::External,
        Network::Testnet,
    )
    .unwrap();
    assert!(validate_descriptor(desc, Network::Testnet));
}
